[package]
name = "pod"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
askama = "0.12.1"
askama_axum = "0.4.0"
axum = { version = "0.7.5", features = ["multipart", "macros"] }
axum-extra = { version = "0.9.3", features = ["cookie-private"] }
base64 = "0.22.1"
chrono = "0.4.38"
dotenv = "0.15.0"
feed-rs = "1.5.2"
mime = "0.3.17"
oauth2 = "4.4.2"
rand = "0.8.5"
reqwest = { version = "0.12.4", default-features = false, features = [
    "rustls-tls",
    "http2",
    "json",
] }
serde = { version = "1.0.203", features = ["serde_derive"] }
serde_json = "1.0.117"
sqlx = { version = "0.8.2", features = [
    "runtime-tokio",
    "postgres",
    "uuid",
    "macros",
    "chrono",
] }
thiserror = "1.0.66"
time = "0.3.36"
tokio = { version = "1.37.0", features = ["full"] }
tower-http = { version = "0.5.2", features = ["cors", "fs"] }
tracing = "0.1.40"
uuid = "1.8.0"
xml = "0.8.20"
